import React, { useEffect, useState } from 'react';
import { CharacterIdentity } from '../../../types';
import { useCharacterStore } from '../../../stores';
import { useCharacterStageStore } from '../../../stores/characterStageStore';
import { PxPalette, PxUser, PxTag, PxChevronDown, PxChevronUp } from '../../shared/PixelIcon';
import { getPaletteColors } from '../../../data/palettes';

const colors = {
  bgPrimary: '#021a1a',
  bgSecondary: '#0d2b2b',
  mint: '#8bd0ba',
  mintMuted: '#8bd0ba40',
  coral: '#f04e4e',
  coralMuted: '#f04e4e40',
  cream: '#d8c8b8',
};

interface IdentityStageProps {
  onGenerateIdentity: () => Promise<void>;
  isGenerating: boolean;
}

export const IdentityStage: React.FC<IdentityStageProps> = ({
  onGenerateIdentity,
  isGenerating,
}) => {
  const { currentIdentity, lockedPalette, description, styleParams } = useCharacterStore();
  const { nextStage, previousStage, isTransitioning, currentStage } = useCharacterStageStore();
  const [notesExpanded, setNotesExpanded] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Auto-generate identity when entering this stage without one
  useEffect(() => {
    if (currentStage === 'identity' && !currentIdentity && !isGenerating && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      onGenerateIdentity();
    }
  }, [currentStage, currentIdentity, isGenerating, hasAutoGenerated, onGenerateIdentity]);

  // Reset auto-generate flag when leaving stage
  useEffect(() => {
    if (currentStage !== 'identity') {
      setHasAutoGenerated(false);
    }
  }, [currentStage]);

  const handleNext = () => {
    if (currentIdentity) {
      nextStage();
    }
  };

  const handleBack = () => {
    previousStage();
  };

  const handleRegenerate = () => {
    onGenerateIdentity();
  };

  const containerStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    width: '100%',
    position: 'relative',
  };

  const panelStyle: React.CSSProperties = {
    backgroundColor: colors.bgSecondary,
    border: `1px solid ${colors.mintMuted}`,
    padding: '32px',
    position: 'relative',
  };

  const headerStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '24px',
  };

  const titleStyle: React.CSSProperties = {
    fontFamily: 'FaytePixel, sans-serif',
    fontSize: '62px',
    fontWeight: 700,
    color: colors.mint,
    letterSpacing: '0.02em',
  };

  const subtitleStyle: React.CSSProperties = {
    fontFamily: 'monospace',
    fontSize: '14px',
    color: colors.cream,
    opacity: 0.7,
    lineHeight: 1.5,
  };

  const stepIndicatorStyle: React.CSSProperties = {
    fontFamily: 'monospace',
    fontSize: '11px',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    color: colors.coral,
    marginBottom: '4px',
  };

  const buttonRowStyle: React.CSSProperties = {
    display: 'flex',
    gap: '12px',
    width: '100%',
  };

  const backButtonStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '16px 24px',
    fontFamily: 'monospace',
    fontSize: '14px',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    backgroundColor: 'transparent',
    border: `2px solid ${colors.mintMuted}`,
    color: colors.cream,
    cursor: isTransitioning || isGenerating ? 'not-allowed' : 'var(--cursor-pointer)',
    opacity: isTransitioning || isGenerating ? 0.6 : 1,
    transition: 'all 0.2s ease',
  };

  const regenerateButtonStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '16px 24px',
    fontFamily: 'monospace',
    fontSize: '14px',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    backgroundColor: 'transparent',
    border: `2px solid ${colors.mint}60`,
    color: colors.mint,
    cursor: isTransitioning || isGenerating ? 'not-allowed' : 'var(--cursor-pointer)',
    opacity: isTransitioning || isGenerating ? 0.6 : 1,
    transition: 'all 0.2s ease',
  };

  const ctaButtonStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    flex: 1,
    padding: '16px 32px',
    fontFamily: 'monospace',
    fontSize: '14px',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    backgroundColor: currentIdentity ? colors.coral : colors.coralMuted,
    border: `2px solid ${currentIdentity ? colors.coral : colors.coralMuted}`,
    color: currentIdentity ? colors.bgPrimary : colors.cream,
    cursor: currentIdentity && !isTransitioning && !isGenerating ? 'var(--cursor-pointer)' : 'not-allowed',
    opacity: isTransitioning || isGenerating ? 0.6 : 1,
    transition: 'all 0.2s ease',
  };

  // Corner bracket CSS
  const cornerBracketCSS = `
    .identity-panel::before,
    .identity-panel::after,
    .identity-panel .corner-bl,
    .identity-panel .corner-tr {
      content: '';
      position: absolute;
      width: 16px;
      height: 16px;
      border-color: ${colors.coral};
      border-style: solid;
      pointer-events: none;
    }
    .identity-panel::before {
      top: -1px;
      left: -1px;
      border-width: 3px 0 0 3px;
    }
    .identity-panel::after {
      bottom: -1px;
      right: -1px;
      border-width: 0 3px 3px 0;
    }
    .identity-panel .corner-tr {
      top: -1px;
      right: -1px;
      border-width: 3px 3px 0 0;
    }
    .identity-panel .corner-bl {
      bottom: -1px;
      left: -1px;
      border-width: 0 0 3px 3px;
    }
    @keyframes identity-pulse {
      0%, 100% { opacity: 0.3; }
      50% { opacity: 0.6; }
    }
    .identity-skeleton {
      background: linear-gradient(90deg, ${colors.mint}15 25%, ${colors.mint}25 50%, ${colors.mint}15 75%);
      background-size: 200% 100%;
      animation: shimmer 1.5s infinite;
    }
    @keyframes shimmer {
      0% { background-position: 200% 0; }
      100% { background-position: -200% 0; }
    }
  `;

  // Loading skeleton
  const LoadingSkeleton = () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Name skeleton */}
      <div className="identity-skeleton" style={{ height: '32px', width: '60%' }} />

      {/* Palette skeleton */}
      <div>
        <div className="identity-skeleton" style={{ height: '14px', width: '120px', marginBottom: '12px' }} />
        <div style={{ display: 'flex', gap: '8px' }}>
          {[...Array(6)].map((_, i) => (
            <div key={i} className="identity-skeleton" style={{ width: '32px', height: '32px' }} />
          ))}
        </div>
      </div>

      {/* Description skeleton */}
      <div>
        <div className="identity-skeleton" style={{ height: '14px', width: '150px', marginBottom: '12px' }} />
        <div style={{ display: 'flex', gap: '12px' }}>
          {[...Array(3)].map((_, i) => (
            <div key={i} className="identity-skeleton" style={{ flex: 1, height: '60px' }} />
          ))}
        </div>
      </div>

      {/* Features skeleton */}
      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
        {[...Array(4)].map((_, i) => (
          <div key={i} className="identity-skeleton" style={{ width: '80px', height: '28px' }} />
        ))}
      </div>
    </div>
  );

  // Identity content display
  const IdentityContent = ({ identity }: { identity: CharacterIdentity }) => {
    const sectionLabelStyle: React.CSSProperties = {
      fontFamily: 'monospace',
      fontSize: '10px',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: '0.15em',
      color: colors.cream,
      opacity: 0.6,
      marginBottom: '8px',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
    };

    const nameStyle: React.CSSProperties = {
      fontFamily: 'FaytePixel, sans-serif',
      fontSize: '24px',
      fontWeight: 700,
      color: colors.mint,
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
      marginBottom: '20px',
    };

    const paletteSwatchStyle = (color: string): React.CSSProperties => ({
      width: '28px',
      height: '28px',
      backgroundColor: color,
      border: `1px solid ${colors.cream}30`,
    });

    const physicalGridStyle: React.CSSProperties = {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '1px',
      backgroundColor: colors.mintMuted,
      border: `1px solid ${colors.mintMuted}`,
    };

    const physicalCellStyle: React.CSSProperties = {
      backgroundColor: colors.bgPrimary,
      padding: '12px',
    };

    const physicalLabelStyle: React.CSSProperties = {
      fontFamily: 'monospace',
      fontSize: '9px',
      textTransform: 'uppercase',
      letterSpacing: '0.1em',
      color: colors.mint,
      opacity: 0.7,
      marginBottom: '4px',
    };

    const physicalValueStyle: React.CSSProperties = {
      fontFamily: 'monospace',
      fontSize: '12px',
      color: colors.cream,
    };

    const featureTagStyle: React.CSSProperties = {
      display: 'inline-block',
      padding: '6px 12px',
      fontFamily: 'monospace',
      fontSize: '11px',
      backgroundColor: `${colors.mint}15`,
      border: `1px solid ${colors.mint}40`,
      color: colors.mint,
    };

    const { name, colourPalette, physicalDescription, distinctiveFeatures, angleNotes } = identity;

    // Show locked palette if available, otherwise selected Lospec palette, otherwise semantic colors
    const selectedPaletteColors = styleParams.paletteMode
      ? getPaletteColors(styleParams.paletteMode)
      : null;

    const paletteColors = lockedPalette && lockedPalette.length > 0
      ? lockedPalette.slice(0, 16)
      : selectedPaletteColors && selectedPaletteColors.length > 0
      ? selectedPaletteColors.slice(0, 16)
      : Object.entries(colourPalette || {})
          .filter(([_, value]) => value)
          .map(([_, value]) => value as string);

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {/* Character Name */}
        <h3 style={nameStyle}>{name}</h3>

        {/* Color Palette */}
        <div>
          <div style={sectionLabelStyle}>
            <PxPalette size={12} />
            <span>{lockedPalette ? 'Locked Palette' : 'Colour Palette'}</span>
          </div>
          <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
            {paletteColors.map((color, index) => (
              <div
                key={index}
                style={paletteSwatchStyle(color)}
                title={color}
              />
            ))}
          </div>
        </div>

        {/* Physical Description */}
        <div>
          <div style={sectionLabelStyle}>
            <PxUser size={12} />
            <span>Physical Description</span>
          </div>
          <div style={physicalGridStyle}>
            <div style={physicalCellStyle}>
              <div style={physicalLabelStyle}>Body Type</div>
              <div style={physicalValueStyle}>{physicalDescription.bodyType}</div>
            </div>
            <div style={physicalCellStyle}>
              <div style={physicalLabelStyle}>Height Style</div>
              <div style={physicalValueStyle}>{physicalDescription.heightStyle}</div>
            </div>
            <div style={physicalCellStyle}>
              <div style={physicalLabelStyle}>Silhouette</div>
              <div style={physicalValueStyle}>{physicalDescription.silhouette}</div>
            </div>
          </div>
        </div>

        {/* Distinctive Features */}
        {distinctiveFeatures && distinctiveFeatures.length > 0 && (
          <div>
            <div style={sectionLabelStyle}>
              <PxTag size={12} />
              <span>Distinctive Features</span>
            </div>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              {distinctiveFeatures.map((feature, index) => (
                <span key={index} style={featureTagStyle}>
                  {feature}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Angle Notes (Collapsible) */}
        {angleNotes && Object.keys(angleNotes).length > 0 && (
          <div style={{ borderTop: `1px solid ${colors.mintMuted}`, paddingTop: '16px' }}>
            <button
              onClick={() => setNotesExpanded(!notesExpanded)}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                width: '100%',
                background: 'none',
                border: 'none',
                padding: 0,
                cursor: 'var(--cursor-pointer)',
                ...sectionLabelStyle,
                marginBottom: notesExpanded ? '12px' : 0,
              }}
            >
              <span>Angle-Specific Notes</span>
              {notesExpanded ? <PxChevronUp size={14} /> : <PxChevronDown size={14} />}
            </button>
            {notesExpanded && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {(['S', 'N', 'E', 'W'] as const).map((direction) => {
                  const note = angleNotes[direction];
                  if (!note) return null;
                  return (
                    <div
                      key={direction}
                      style={{
                        borderLeft: `2px solid ${colors.mint}60`,
                        paddingLeft: '12px',
                        paddingTop: '4px',
                        paddingBottom: '4px',
                      }}
                    >
                      <div style={{ ...physicalLabelStyle, marginBottom: '2px' }}>{direction}</div>
                      <div style={{ fontFamily: 'monospace', fontSize: '11px', color: colors.cream, opacity: 0.8 }}>
                        {note}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>
    );
  };

  return (
    <>
      <style>{cornerBracketCSS}</style>
      <div style={containerStyle}>
        <div className="identity-panel" style={panelStyle}>
          {/* Corner bracket elements */}
          <span className="corner-tr" />
          <span className="corner-bl" />

          {/* Header */}
          <div style={headerStyle}>
            <span style={stepIndicatorStyle}>Step 03</span>
            <h2 style={titleStyle}>Character Identity</h2>
            <p style={subtitleStyle}>
              {isGenerating
                ? 'Generating your character identity...'
                : currentIdentity
                ? 'Review your character identity. Regenerate if needed.'
                : 'Your character identity will be generated automatically.'}
            </p>
          </div>

          {/* Identity Content or Loading */}
          {isGenerating ? (
            <LoadingSkeleton />
          ) : currentIdentity ? (
            <IdentityContent identity={currentIdentity} />
          ) : (
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '40px',
              color: colors.cream,
              opacity: 0.5,
            }}>
              <PxUser size={48} style={{ marginBottom: '16px' }} />
              <span style={{ fontFamily: 'monospace', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                No Identity Generated
              </span>
            </div>
          )}
        </div>

        {/* Button Row */}
        <div style={buttonRowStyle}>
          <button
            style={backButtonStyle}
            onClick={handleBack}
            disabled={isTransitioning || isGenerating}
            onMouseEnter={(e) => {
              if (!isTransitioning && !isGenerating) {
                e.currentTarget.style.backgroundColor = `${colors.mint}15`;
                e.currentTarget.style.borderColor = colors.mint;
              }
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.backgroundColor = 'transparent';
              e.currentTarget.style.borderColor = colors.mintMuted;
            }}
          >
            <span style={{ fontSize: '16px' }}>{'<'}</span>
            <span>Back</span>
          </button>

          {currentIdentity && (
            <button
              style={regenerateButtonStyle}
              onClick={handleRegenerate}
              disabled={isTransitioning || isGenerating}
              onMouseEnter={(e) => {
                if (!isTransitioning && !isGenerating) {
                  e.currentTarget.style.backgroundColor = `${colors.mint}20`;
                  e.currentTarget.style.borderColor = colors.mint;
                }
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = 'transparent';
                e.currentTarget.style.borderColor = `${colors.mint}60`;
              }}
            >
              Regenerate
            </button>
          )}

          <button
            style={ctaButtonStyle}
            onClick={handleNext}
            disabled={!currentIdentity || isTransitioning || isGenerating}
            onMouseEnter={(e) => {
              if (currentIdentity && !isTransitioning && !isGenerating) {
                e.currentTarget.style.backgroundColor = '#ff6b6b';
                e.currentTarget.style.borderColor = '#ff6b6b';
                e.currentTarget.style.transform = 'translateY(-1px)';
              }
            }}
            onMouseLeave={(e) => {
              if (currentIdentity && !isTransitioning && !isGenerating) {
                e.currentTarget.style.backgroundColor = colors.coral;
                e.currentTarget.style.borderColor = colors.coral;
                e.currentTarget.style.transform = 'translateY(0)';
              }
            }}
          >
            <span>Open Canvas</span>
            <span style={{ fontSize: '16px' }}>{'>'}</span>
          </button>
        </div>
      </div>
    </>
  );
};

export default IdentityStage;
